from db.setup import *

class StatTable(Base):
    __tablename__ = 'stats'

    id = Column(Integer, Sequence('regular_stats_id_seq'), primary_key=True)
    player_id = Column(Integer, ForeignKey('players.id'))
    year_id = Column(Integer, ForeignKey('years.id'))
    type_id = Column(Integer, ForeignKey('table_types.id'))
    games = Column(Integer)
    games_started = Column(Integer)
    minutes_played = Column(Integer)
    fgs = Column(Float)
    fg_attempts = Column(Float)
    fg_percent = Column(Float)
    th_fgs = Column(Float)
    th_fg_attempts = Column(Float)
    th_fg_percent = Column(Float)
    tw_fgs = Column(Float)
    tw_fg_attempts = Column(Float)
    tw_fg_percent = Column(Float)
    fts = Column(Float)
    ft_attempts = Column(Float)
    ft_percent = Column(Float)
    off_rebound = Column(Float)
    def_rebound = Column(Float)
    rebounds = Column(Float)
    assists = Column(Float)
    steals = Column(Float)
    blocks = Column(Float)
    turnovers = Column(Float)
    fouls = Column(Float)
    points = Column(Float)

    player = relationship("Player", backref=backref('stat_tables', order_by=id))
    year = relationship("Year")
    type = relationship("TableType")